### ISSUE TITLE
Link missing diredtion personal see /c

/:#
Ppp must direct to me happy to explore motion of poetry more than constellations gift one man .generous man yet to solve must insight to resolve . Magic of pure heart must pre for taste   

### ISSUE THREAD

**Issue by Startmyg1t** [AnnaCanada/python-project-lvl1#1]
Watch my 6 I stand to help for I am the 1 man flow chart  or poet  invite  to complete your mission then we have the meal job _ core ##above... .... ...
I am praying and help...

**Comment by annashch-git** [comment]
Am sorry, I don't understand.

**Comment by Startmyg1t** [comment]
Sorry can u try notetredomis js does that make sense

**Comment by Startmyg1t** [comment]
Brotherhood of notable domestic pre sey school library and will you sign to a commission with of coarse github fee for more assignments

**Comment by annashch-git** [comment]
This is some kind of spam.
